import { getDb } from "../api/queries/connection";
import { galleryItems } from "./schema";

const al = (kw: string) => `https://www.amazon.in/s?k=${encodeURIComponent(kw)}&tag=5010b3-21`;

const items = [
  // ===== WEEK 1: Popular & Trending =====
  {
    caption: "Boho Living Room",
    description: "A warm, eclectic boho living space featuring rattan furniture, macrame wall hangings, colorful patterned rugs, and abundant indoor plants.",
    image: "images/gallery/item1.jpg",
    style: "Boho",
    weekSlot: "W1",
    products: [
      { name: "Rattan 3-Seater Sofa", price: 22000, link: al("rattan sofa 3 seater"), category: "Furniture" },
      { name: "Macrame Wall Hanging Set", price: 1800, link: al("macrame wall hanging set boho"), category: "Decor" },
      { name: "Persian Pattern Area Rug", price: 4500, link: al("persian area rug 5x7"), category: "Rug" },
      { name: "Woven Pouf Ottomans (Set of 2)", price: 3200, link: al("woven pouf ottoman set"), category: "Seating" },
      { name: "Hanging Planter Set", price: 1200, link: al("hanging planters indoor set"), category: "Plants" },
      { name: "Brass Table Lamp", price: 2800, link: al("brass table lamp antique"), category: "Lighting" },
      { name: "Handwoven Throw Blankets", price: 1500, link: al("handwoven throw blanket cotton"), category: "Textiles" },
      { name: "Vintage Floor Cushions", price: 2500, link: al("floor cushions boho vintage"), category: "Seating" },
    ],
    changes: [
      { title: "Layer Textiles", description: "Add 3-5 patterned rugs overlapping on the floor. Mix Persian, Moroccan, and kilim styles." },
      { title: "Add Macrame & Wall Decor", description: "Hang 2-3 macrame pieces on the main wall. Mix with woven baskets and vintage mirrors." },
      { title: "Bring in Plants", description: "Place 5-7 indoor plants of varying sizes. Use hanging planters near windows." },
      { title: "Swap for Natural Furniture", description: "Replace metal/plastic furniture with rattan, bamboo, or reclaimed wood pieces." },
      { title: "Add Floor Cushions", description: "Scatter 4-6 floor cushions and poufs around the coffee table for casual seating." },
      { title: "Warm Lighting", description: "Switch to warm Edison bulbs and add brass/copper table lamps." },
    ],
    colors: [{ name: "Terracotta", hex: "#E2725B" }, { name: "Mustard", hex: "#D4A017" }, { name: "Olive", hex: "#808000" }, { name: "Cream", hex: "#FFFDD0" }, { name: "Rust", hex: "#B7410E" }],
    totalBudget: 39500, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },
  {
    caption: "Modern Kitchen",
    description: "A stunning kitchen renovation featuring white cabinets with gold handles, marble countertops, and elegant pendant lighting.",
    image: "images/gallery/item6.jpg", style: "Modern", weekSlot: "W1",
    products: [
      { name: "Kitchen Island with Marble Top", price: 35000, link: al("kitchen island marble top movable"), category: "Furniture" },
      { name: "Bar Stools with Gold Legs (Set of 2)", price: 8000, link: al("bar stools gold legs velvet set of 2"), category: "Seating" },
      { name: "Glass Pendant Lights (Set of 3)", price: 4500, link: al("glass pendant lights kitchen island set of 3"), category: "Lighting" },
      { name: "Open Wall Shelf Rack", price: 2500, link: al("open wall shelf rack kitchen"), category: "Storage" },
      { name: "Ceramic Dinner Set (24 pcs)", price: 3500, link: al("ceramic dinner set 24 pieces white"), category: "Tableware" },
      { name: "Gold Cabinet Handles (Set)", price: 1500, link: al("gold cabinet handles brass drawer pulls set"), category: "Hardware" },
      { name: "Marble Cutting Board", price: 1200, link: al("marble cutting board white cheese board"), category: "Kitchen" },
      { name: "Copper Cookware Set", price: 8500, link: al("copper cookware set pots pans hammered"), category: "Kitchen" },
    ],
    changes: [
      { title: "Upgrade Cabinet Hardware", description: "Replace old handles with brushed gold or brass ones. Instant luxury upgrade." },
      { title: "Add a Kitchen Island", description: "Install a freestanding island with storage. Use it as prep space and breakfast bar." },
      { title: "Install Pendant Lighting", description: "Hang 2-3 glass or copper pendant lights above the island." },
      { title: "Open Up Storage", description: "Remove upper cabinet doors or replace with open shelving." },
      { title: "Use Marble Accents", description: "Add marble-look countertops or a marble cutting board." },
      { title: "Coordinate Metals", description: "Pick one metal finish and use it consistently for handles, faucets, and lights." },
    ],
    colors: [{ name: "Pure White", hex: "#FFFFFF" }, { name: "Carrara Marble", hex: "#F0EFEA" }, { name: "Brushed Gold", hex: "#C9A961" }, { name: "Soft Grey", hex: "#B0B0B0" }, { name: "Sage Green", hex: "#A8BFA3" }],
    totalBudget: 65700, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },
  {
    caption: "Small Bedroom Makeover",
    description: "A clever small bedroom transformation using space-saving furniture, floating shelves, warm string lights, and a compact workspace.",
    image: "images/gallery/item5.jpg", style: "Minimalist", weekSlot: "W1",
    products: [
      { name: "Storage Bed with Drawers", price: 18000, link: al("storage bed queen size with drawers"), category: "Furniture" },
      { name: "Floating Wall Shelves (Set)", price: 1500, link: al("floating wall shelves set of 3"), category: "Storage" },
      { name: "LED String Lights", price: 800, link: al("LED string lights warm white bedroom"), category: "Lighting" },
      { name: "Foldable Wall-Mounted Desk", price: 4500, link: al("foldable wall mounted desk study"), category: "Furniture" },
      { name: "Full-Length Mirror", price: 2500, link: al("full length mirror wall mounted"), category: "Decor" },
      { name: "Under-Bed Storage Boxes", price: 1200, link: al("under bed storage boxes with wheels"), category: "Storage" },
      { name: "Slim Nightstand", price: 2500, link: al("slim nightstand narrow bedside table"), category: "Furniture" },
      { name: "Blackout Curtains", price: 2000, link: al("blackout curtains thermal insulated"), category: "Textiles" },
    ],
    changes: [
      { title: "Use Multi-Functional Furniture", description: "Get a storage bed with drawers. Use a foldable wall desk that disappears when not needed." },
      { title: "Install Floating Shelves", description: "Replace floor bookshelves with floating wall shelves. Keep the floor clear." },
      { title: "Add a Large Mirror", description: "Place a full-length mirror on one wall to create the illusion of double the space." },
      { title: "Hang String Lights", description: "Drape warm LED string lights along the headboard for cozy ambiance." },
      { title: "Choose Light Colors", description: "Paint walls in whites, creams, or soft pastels. Dark colors make rooms feel cramped." },
      { title: "Maximize Vertical Space", description: "Use tall wardrobes and stackable storage. Go vertical when you cannot go horizontal." },
    ],
    colors: [{ name: "Warm White", hex: "#F5F2EA" }, { name: "Soft Grey", hex: "#D3D3D3" }, { name: "Blush Pink", hex: "#F4C2C2" }, { name: "Light Wood", hex: "#DEB887" }, { name: "Sage Green", hex: "#9DC183" }],
    totalBudget: 33000, timeEstimate: "1-2 weekends", difficulty: "Easy",
  },
  {
    caption: "Smart Home Living",
    description: "A futuristic smart home living room with sleek white entertainment units, hidden LED lighting, and integrated automation.",
    image: "images/gallery/item4.jpg", style: "Smart Home", weekSlot: "W1",
    products: [
      { name: "Smart LED Strip Lights", price: 2500, link: al("smart LED strip lights RGB wifi"), category: "Lighting" },
      { name: "Motorized Curtain Rod", price: 8500, link: al("motorized curtain rod automatic"), category: "Automation" },
      { name: "Smart Speaker System", price: 12000, link: al("smart speaker home system echo"), category: "Tech" },
      { name: "White Entertainment Unit", price: 15000, link: al("white entertainment unit TV cabinet"), category: "Furniture" },
      { name: "Smart Plug Set (4-pack)", price: 2000, link: al("smart plug wifi 4 pack"), category: "Automation" },
      { name: "Touch Panel Dimmer", price: 3500, link: al("touch panel dimmer switch glass"), category: "Lighting" },
      { name: "Wireless Charging Side Table", price: 6000, link: al("wireless charging side table nightstand"), category: "Furniture" },
      { name: "Smart Thermostat", price: 8000, link: al("smart thermostat wifi programmable"), category: "Tech" },
    ],
    changes: [
      { title: "Install LED Strip Lighting", description: "Add RGB LED strips behind the TV unit, under shelves, and along ceiling coves." },
      { title: "Automate Curtains", description: "Replace manual curtain rods with motorized ones. Schedule via smartphone app." },
      { title: "Centralize Entertainment", description: "Get a sleek white entertainment unit with cable management. Mount TV with hidden wiring." },
      { title: "Add Smart Plugs", description: "Convert all lamps and appliances to smart control. Create scenes like Movie Night." },
      { title: "Upgrade to Touch Controls", description: "Replace traditional switches with glass touch panels and dimmer controls." },
      { title: "Minimize Visual Clutter", description: "Use wireless charging furniture. Hide all cables. Keep surfaces clear." },
    ],
    colors: [{ name: "Pure White", hex: "#FAFAFA" }, { name: "Arctic Blue", hex: "#E0F2F7" }, { name: "Graphite", hex: "#474747" }, { name: "Silver", hex: "#C0C0C0" }, { name: "Neon Accent", hex: "#39FF14" }],
    totalBudget: 57500, timeEstimate: "1-2 weekends", difficulty: "Easy",
  },
  {
    caption: "Teen Bedroom Ideas",
    description: "A trendy teen bedroom featuring neon LED signs, colorful bedding, a gaming desk setup, and polaroid photo walls.",
    image: "images/gallery/item8.jpg", style: "Teen", weekSlot: "W1",
    products: [
      { name: "Neon LED Name Sign", price: 2500, link: al("custom neon LED sign name bedroom"), category: "Lighting" },
      { name: "RGB LED Strip (5m)", price: 1500, link: al("RGB LED strip lights 5m bluetooth app control"), category: "Lighting" },
      { name: "Gaming Desk Setup", price: 12000, link: al("gaming desk setup LED carbon fiber"), category: "Furniture" },
      { name: "Colorful Bedding Set", price: 3500, link: al("colorful bedding set queen teen aesthetic"), category: "Textiles" },
      { name: "Polaroid Photo String Lights", price: 800, link: al("polaroid photo clip string lights LED"), category: "Decor" },
      { name: "Bean Bag Chair", price: 3500, link: al("bean bag chair XXXL with filling"), category: "Seating" },
      { name: "Tapestry Wall Hanging", price: 1200, link: al("tapestry wall hanging aesthetic bohemian"), category: "Decor" },
      { name: "Desk Organizer with Charger", price: 2000, link: al("desk organizer wireless charger pen holder"), category: "Accessories" },
    ],
    changes: [
      { title: "Create a Feature Wall", description: "Use a tapestry, removable wallpaper, or photo collage as a statement wall." },
      { title: "Add Neon & LED Accents", description: "Install a custom neon sign and RGB LED strips behind the desk and bed." },
      { title: "Set Up Gaming/Study Zone", description: "Dedicate one corner to a gaming desk with cable management and dual monitors." },
      { title: "Display Photos Creatively", description: "Use polaroid-style string lights or a wire grid for photos and mementos." },
      { title: "Mix Patterns & Colors", description: "Let personality shine through bold bedding, patterned rugs, and colorful decor." },
      { title: "Add Casual Seating", description: "Include a bean bag or floor chair for friends to hang out." },
    ],
    colors: [{ name: "Electric Pink", hex: "#FF10F0" }, { name: "Neon Blue", hex: "#00FFFF" }, { name: "Purple Haze", hex: "#BF40BF" }, { name: "Black", hex: "#1A1A1A" }, { name: "Soft Lavender", hex: "#E6E6FA" }],
    totalBudget: 27000, timeEstimate: "1 weekend", difficulty: "Easy",
  },

  // ===== WEEK 2: Global & Cultural =====
  {
    caption: "Traditional Indian",
    description: "A vibrant Indian apartment featuring carved wooden furniture, brass accents, colorful textiles, and decorative mirrors.",
    image: "images/gallery/item3.jpg", style: "Traditional Indian", weekSlot: "W2",
    products: [
      { name: "Carved Sheesham Wood Sofa", price: 28000, link: al("carved sheesham wood sofa set"), category: "Furniture" },
      { name: "Brass Urli Bowl", price: 1500, link: al("brass urli bowl decorative"), category: "Decor" },
      { name: "Handwoven Dhurrie Rug", price: 3500, link: al("handwoven dhurrie rug indian"), category: "Rug" },
      { name: "Decorative Brass Mirror", price: 4200, link: al("decorative brass wall mirror round"), category: "Decor" },
      { name: "Silk Cushion Covers (Set of 5)", price: 2000, link: al("silk cushion covers set of 5"), category: "Textiles" },
      { name: "Wooden Swing Jhula", price: 18000, link: al("indoor wooden swing jhula"), category: "Furniture" },
      { name: "Terracotta Pot Set", price: 1200, link: al("terracotta pots decorative set"), category: "Decor" },
      { name: "Marble Inlay Side Table", price: 5500, link: al("marble inlay side table pietra dura"), category: "Furniture" },
    ],
    changes: [
      { title: "Add Carved Wood Furniture", description: "Replace modern furniture with sheesham or teak pieces featuring traditional Indian carvings." },
      { title: "Layer Indian Textiles", description: "Use silk, brocade, and block-printed fabrics for cushions, throws, and curtains." },
      { title: "Incorporate Brass & Copper", description: "Add brass urli bowls, copper planters, and metal artifacts as decor." },
      { title: "Hang Decorative Mirrors", description: "Install arched or round brass-framed mirrors as a wall feature." },
      { title: "Use Warm Lighting", description: "Switch to warm yellow lighting. Add diyas or LED tea lights for evening ambiance." },
      { title: "Add an Indoor Swing", description: "Install a wooden jhula — the centerpiece of traditional Indian living rooms." },
    ],
    colors: [{ name: "Marigold", hex: "#F4A460" }, { name: "Teal", hex: "#008080" }, { name: "Deep Red", hex: "#C41E3A" }, { name: "Ivory", hex: "#FFFFF0" }, { name: "Saffron", hex: "#F4C430" }],
    totalBudget: 63900, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },
  {
    caption: "Mediterranean Courtyard",
    description: "A Mediterranean courtyard with whitewashed stucco walls, terracotta tiles, wrought iron furniture, and climbing bougainvillea.",
    image: "images/gallery/mediterranean.jpg", style: "Mediterranean", weekSlot: "W2",
    products: [
      { name: "Wrought Iron Sofa Set", price: 28000, link: al("wrought iron sofa set outdoor patio"), category: "Furniture" },
      { name: "Terracotta Floor Tiles", price: 15000, link: al("terracotta floor tiles rustic"), category: "Flooring" },
      { name: "Mosaic Tile Fountain", price: 8000, link: al("mosaic tile fountain indoor table"), category: "Decor" },
      { name: "Blue Ceramic Vase Set", price: 2500, link: al("blue ceramic vase set mediterranean"), category: "Decor" },
      { name: "Olive Tree in Terracotta Pot", price: 3500, link: al("artificial olive tree potted tall"), category: "Plants" },
      { name: "Striped Outdoor Cushions", price: 1800, link: al("outdoor cushions blue white stripes"), category: "Textiles" },
      { name: "Wrought Iron Candle Holder", price: 1200, link: al("wrought iron candle holder floor"), category: "Decor" },
      { name: "Arched Wall Mirror", price: 4500, link: al("arched wall mirror iron frame"), category: "Decor" },
    ],
    changes: [
      { title: "Paint Walls White", description: "Use whitewashed stucco or textured white paint on walls for that Santorini feel." },
      { title: "Add Terracotta Elements", description: "Use terracotta pots, tiles, and accents throughout the space." },
      { title: "Install Wrought Iron Furniture", description: "Choose wrought iron or forged metal frames for seating and tables." },
      { title: "Use Blue & White Palette", description: "Accent with cobalt blue ceramics, tiles, and textiles against white walls." },
      { title: "Add a Water Feature", description: "Install a small mosaic fountain for the soothing sound of water." },
      { title: "Grow Climbing Plants", description: "Train bougainvillea or jasmine on archways and trellises." },
    ],
    colors: [{ name: "Santorini White", hex: "#F5F5F0" }, { name: "Cobalt Blue", hex: "#0047AB" }, { name: "Terracotta", hex: "#E2725B" }, { name: "Olive Green", hex: "#808000" }, { name: "Wrought Iron", hex: "#2C2C2C" }],
    totalBudget: 64500, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },
  {
    caption: "Moroccan Living Room",
    description: "A Moroccan inspired living room with intricate geometric tiles, colorful patterned poufs, brass tray tables, and rich jewel tones.",
    image: "images/gallery/moroccan.jpg", style: "Moroccan", weekSlot: "W2",
    products: [
      { name: "Brass Tray Table", price: 5500, link: al("brass tray table moroccan engraved"), category: "Furniture" },
      { name: "Colorful Kilim Poufs (Set of 3)", price: 3500, link: al("kilim pouf ottoman set of 3 moroccan"), category: "Seating" },
      { name: "Mosaic Floor Lamp", price: 4500, link: al("mosaic floor lamp turkish moroccan"), category: "Lighting" },
      { name: "Carved Wooden Screen", price: 8000, link: al("carved wooden screen room divider"), category: "Decor" },
      { name: "Silk Cushion Covers (Set of 6)", price: 3000, link: al("silk cushion covers set jewel tones"), category: "Textiles" },
      { name: "Moroccan Area Rug", price: 6000, link: al("moroccan beni ourain rug"), category: "Rug" },
      { name: "Brass Lantern Pendant", price: 3500, link: al("brass lantern pendant light moroccan"), category: "Lighting" },
      { name: "Copper Tea Set", price: 2500, link: al("copper tea set moroccan engraved"), category: "Decor" },
    ],
    changes: [
      { title: "Add Geometric Tile Work", description: "Use zellige or mosaic tiles on an accent wall or as a backsplash." },
      { title: "Layer Colorful Poufs", description: "Scatter kilim and leather poufs around a low brass tray table." },
      { title: "Install a Carved Screen", description: "Use an ornate wooden screen as a room divider or wall accent." },
      { title: "Hang a Brass Lantern", description: "Install a pierced brass lantern that casts beautiful light patterns." },
      { title: "Layer Rich Textiles", description: "Use silk, velvet, and embroidered fabrics in jewel tones." },
      { title: "Use Rich Jewel Tones", description: "Decorate with emerald, sapphire, ruby, and gold accents." },
    ],
    colors: [{ name: "Emerald", hex: "#2D5A3D" }, { name: "Sapphire Blue", hex: "#0F52BA" }, { name: "Ruby Red", hex: "#9B111E" }, { name: "Gold", hex: "#D4AF37" }, { name: "Deep Purple", hex: "#4A0E4E" }],
    totalBudget: 36500, timeEstimate: "2 weekends", difficulty: "Medium",
  },
  {
    caption: "Zen Meditation Room",
    description: "A zen minimalist meditation room with low wooden platform, shoji screens, paper lanterns, and a natural stone water feature.",
    image: "images/gallery/zen.jpg", style: "Zen", weekSlot: "W2",
    products: [
      { name: "Low Wooden Meditation Platform", price: 8000, link: al("meditation platform low wooden japanese"), category: "Furniture" },
      { name: "Shoji Screen Room Divider", price: 6000, link: al("shoji screen room divider rice paper"), category: "Decor" },
      { name: "Paper Lantern Pendant Set", price: 1500, link: al("paper lantern pendant light japanese"), category: "Lighting" },
      { name: "Natural Stone Water Feature", price: 4500, link: al("indoor water fountain stone zen"), category: "Decor" },
      { name: "Tatami Mat Flooring", price: 5000, link: al("tatami mat flooring japanese style"), category: "Flooring" },
      { name: "Round Zafu Meditation Cushion", price: 1200, link: al("zafu meditation cushion buckwheat"), category: "Seating" },
      { name: "Ikebana Flower Vase", price: 800, link: al("ikebana vase ceramic japanese"), category: "Decor" },
      { name: "Incense Holder Set", price: 500, link: al("incense holder set zen ceramic"), category: "Decor" },
    ],
    changes: [
      { title: "Install Tatami Mats", description: "Replace flooring with tatami mats or natural woven flooring." },
      { title: "Add Shoji Screens", description: "Use rice paper screens to divide space and diffuse natural light." },
      { title: "Create a Water Feature", description: "Install a small recirculating water fountain with stacked stones." },
      { title: "Use Paper Lanterns", description: "Hang washi paper lanterns for soft, warm ambient lighting." },
      { title: "Minimize Furniture", description: "Keep only essential pieces. Use a low platform instead of a table." },
      { title: "Add a Single Ikebana", description: "Place one carefully arranged flower as the only decorative element." },
    ],
    colors: [{ name: "Rice Paper", hex: "#F0EDE5" }, { name: "Stone Grey", hex: "#8C8C8C" }, { name: "Bamboo", hex: "#C8A951" }, { name: "Charcoal Ink", hex: "#2C2C2C" }, { name: "Moss Green", hex: "#7A8B6F" }],
    totalBudget: 27500, timeEstimate: "1-2 weekends", difficulty: "Easy",
  },
  {
    caption: "Korean Minimalist Bedroom",
    description: "A Korean-inspired minimalist bedroom with low wooden platform bed, paper lantern, sliding doors, and understated elegance.",
    image: "images/gallery/korean.jpg", style: "Korean", weekSlot: "W2",
    products: [
      { name: "Low Platform Bed Frame", price: 15000, link: al("low platform bed frame wooden korean"), category: "Furniture" },
      { name: "Paper Globe Pendant Light", price: 1800, link: al("paper globe pendant light large"), category: "Lighting" },
      { name: "Wooden Sliding Door Set", price: 12000, link: al("wooden sliding door room divider"), category: "Furniture" },
      { name: "Low Tea Table Set", price: 2500, link: al("low tea table korean wooden"), category: "Furniture" },
      { name: "Ceramic Tea Set", price: 1500, link: al("korean ceramic tea set white"), category: "Decor" },
      { name: "Bonsai Tree", price: 2500, link: al("bonsai tree indoor juniper"), category: "Plants" },
      { name: "Linen Bedding Set", price: 3500, link: al("linen bedding set white queen"), category: "Textiles" },
      { name: "Woven Storage Basket Set", price: 1200, link: al("woven storage basket set rattan"), category: "Storage" },
    ],
    changes: [
      { title: "Use a Low Platform Bed", description: "Sleep close to the floor on a simple wooden platform with quality linen." },
      { title: "Install Sliding Doors", description: "Use wooden sliding doors instead of hinged ones for a seamless look." },
      { title: "Add a Paper Lantern", description: "Use a large paper globe pendant as the primary light source." },
      { title: "Create a Tea Corner", description: "Set up a low table with a ceramic tea set for a daily ritual space." },
      { title: "Keep It Minimal", description: "Remove all unnecessary items. Each piece should have purpose and beauty." },
      { title: "Use Natural Materials", description: "Choose wood, linen, ceramic, and stone over synthetic materials." },
    ],
    colors: [{ name: "Warm White", hex: "#F5F2EA" }, { name: "Natural Oak", hex: "#C4A484" }, { name: "Soft Grey", hex: "#B0B0B0" }, { name: "Charcoal", hex: "#36454F" }, { name: "Linen", hex: "#E8DCC8" }],
    totalBudget: 40000, timeEstimate: "1-2 weekends", difficulty: "Easy",
  },

  // ===== WEEK 3: Classic & Timeless =====
  {
    caption: "Industrial Loft",
    description: "Raw industrial loft with exposed brick walls, steel beams, leather sofa, Edison bulb lighting, and reclaimed wood furniture.",
    image: "images/gallery/item2.jpg", style: "Industrial", weekSlot: "W3",
    products: [
      { name: "Leather Chesterfield Sofa", price: 35000, link: al("leather chesterfield sofa 3 seater"), category: "Furniture" },
      { name: "Reclaimed Wood Coffee Table", price: 8500, link: al("reclaimed wood coffee table industrial"), category: "Furniture" },
      { name: "Edison Bulb Pendant Light", price: 3800, link: al("edison bulb pendant light vintage"), category: "Lighting" },
      { name: "Metal Bar Stools (Set of 2)", price: 6000, link: al("metal bar stools industrial set of 2"), category: "Seating" },
      { name: "Vintage Factory Clock", price: 2200, link: al("vintage factory wall clock industrial"), category: "Decor" },
      { name: "Iron Pipe Bookshelf", price: 7500, link: al("iron pipe bookshelf industrial vintage"), category: "Storage" },
      { name: "Concrete Planters (Set)", price: 1800, link: al("concrete planters set modern"), category: "Plants" },
      { name: "Distressed Area Rug", price: 4200, link: al("distressed area rug vintage industrial"), category: "Rug" },
    ],
    changes: [
      { title: "Expose Raw Materials", description: "Remove plaster to expose brick walls, or use brick wallpaper." },
      { title: "Install Edison Lighting", description: "Replace ceiling fixtures with exposed Edison bulb pendants." },
      { title: "Add Metal Accents", description: "Introduce wrought iron, steel, and copper elements." },
      { title: "Choose Leather & Wood", description: "Opt for distressed leather sofas and reclaimed wood tables." },
      { title: "Use a Neutral Palette", description: "Stick to greys, blacks, browns, and cream." },
      { title: "Open the Space", description: "Minimize partitions. Use open shelving instead of closed cabinets." },
    ],
    colors: [{ name: "Concrete Grey", hex: "#989898" }, { name: "Brick Red", hex: "#A0522D" }, { name: "Steel Blue", hex: "#4682B4" }, { name: "Raw Wood", hex: "#8B6914" }, { name: "Matte Black", hex: "#2B2B2B" }],
    totalBudget: 69000, timeEstimate: "3-4 weekends", difficulty: "Advanced",
  },
  {
    caption: "Art Deco Living Room",
    description: "A glamorous Art Deco living room with geometric patterns, gold and black palette, velvet sofa, and crystal chandelier.",
    image: "images/gallery/artdeco.jpg", style: "Art Deco", weekSlot: "W3",
    products: [
      { name: "Velvet Emerald Green Sofa", price: 35000, link: al("velvet emerald green sofa 3 seater"), category: "Furniture" },
      { name: "Sunburst Gold Mirror", price: 5500, link: al("sunburst gold wall mirror large"), category: "Decor" },
      { name: "Crystal Chandelier", price: 12000, link: al("crystal chandelier modern art deco"), category: "Lighting" },
      { name: "Marble Side Table with Brass Legs", price: 4500, link: al("marble side table brass legs round"), category: "Furniture" },
      { name: "Geometric Chevron Rug", price: 5000, link: al("geometric chevron rug black gold"), category: "Rug" },
      { name: "Gold Wall Sconces (Pair)", price: 3500, link: al("gold wall sconces pair art deco"), category: "Lighting" },
      { name: "White Feather Vase Arrangement", price: 2500, link: al("white feather vase arrangement decorative"), category: "Decor" },
      { name: "Gold Bar Cart", price: 8000, link: al("gold bar cart art deco vintage"), category: "Furniture" },
    ],
    changes: [
      { title: "Use Bold Geometric Patterns", description: "Add chevron, sunburst, and zigzag patterns in rugs and wall decor." },
      { title: "Install a Statement Chandelier", description: "Hang a crystal or geometric chandelier as the room's centerpiece." },
      { title: "Choose Luxurious Materials", description: "Use velvet, marble, brass, and lacquered surfaces." },
      { title: "Add a Sunburst Mirror", description: "Install a gold sunburst mirror as a focal point above the sofa." },
      { title: "Use a Gold & Black Palette", description: "Combine black walls or furniture with gold accents throughout." },
      { title: "Add Velvet Upholstery", description: "Use emerald green, sapphire blue, or ruby red velvet for seating." },
    ],
    colors: [{ name: "Emerald", hex: "#2D5A3D" }, { name: "Gold", hex: "#D4AF37" }, { name: "Black", hex: "#1A1A1A" }, { name: "Cream", hex: "#FFFFF0" }, { name: "Navy", hex: "#1B2A4A" }],
    totalBudget: 76000, timeEstimate: "2-3 weekends", difficulty: "Advanced",
  },
  {
    caption: "Mid-Century Modern Living",
    description: "A mid-century modern living room with teak wood furniture, orange accent chair, geometric rug, and walnut credenza.",
    image: "images/gallery/midcentury.jpg", style: "Mid-Century Modern", weekSlot: "W3",
    products: [
      { name: "Teak Wood Sofa", price: 28000, link: al("teak wood sofa mid century modern"), category: "Furniture" },
      { name: "Orange Accent Armchair", price: 12000, link: al("orange accent chair mid century modern"), category: "Seating" },
      { name: "Walnut Credenza with Tapered Legs", price: 18000, link: al("walnut credenza mid century tapered legs"), category: "Furniture" },
      { name: "Arc Floor Lamp", price: 6500, link: al("arc floor lamp marble base brass"), category: "Lighting" },
      { name: "Geometric Patterned Rug", price: 4500, link: al("geometric patterned rug warm tones mid century"), category: "Rug" },
      { name: "Abstract Wall Art Set", price: 2500, link: al("abstract wall art set canvas mid century"), category: "Decor" },
      { name: "Teak Coffee Table", price: 8500, link: al("teak coffee table oval mid century"), category: "Furniture" },
      { name: "Ceramic Table Lamp Set", price: 2500, link: al("ceramic table lamp set retro mid century"), category: "Lighting" },
    ],
    changes: [
      { title: "Choose Teak & Walnut", description: "Opt for warm wood tones like teak, walnut, and rosewood for furniture." },
      { title: "Add Bold Accent Colors", description: "Use orange, mustard, or teal as accent colors against neutral backgrounds." },
      { title: "Install an Arc Lamp", description: "Place an arc floor lamp over the seating area for dramatic lighting." },
      { title: "Use Tapered Legs", description: "Choose furniture with hairpin or tapered legs for that signature look." },
      { title: "Add Abstract Art", description: "Hang abstract or atomic-style artwork in warm, complementary colors." },
      { title: "Pick a Geometric Rug", description: "Use a rug with atomic, starburst, or geometric patterns." },
    ],
    colors: [{ name: "Mustard", hex: "#D4A017" }, { name: "Teal", hex: "#008080" }, { name: "Walnut", hex: "#6B4F3A" }, { name: "Burnt Orange", hex: "#CC5500" }, { name: "Olive", hex: "#808000" }],
    totalBudget: 82500, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },
  {
    caption: "French Country Dining",
    description: "A French country dining room with distressed white table, upholstered linen chairs, crystal chandelier, and vintage hutch.",
    image: "images/gallery/frenchcountry.jpg", style: "French Country", weekSlot: "W3",
    products: [
      { name: "Distressed White Dining Table", price: 25000, link: al("distressed white dining table french country"), category: "Furniture" },
      { name: "Linen Upholstered Dining Chairs (Set of 6)", price: 18000, link: al("linen dining chairs set of 6 french country"), category: "Seating" },
      { name: "Crystal Chandelier", price: 8000, link: al("crystal chandelier french country vintage"), category: "Lighting" },
      { name: "Vintage Display Hutch", price: 15000, link: al("vintage display hutch cabinet white distressed"), category: "Storage" },
      { name: "Antique Gold Mirror", price: 4500, link: al("antique gold mirror ornate large"), category: "Decor" },
      { name: "Toile Curtain Panels", price: 2500, link: al("toile curtains panels blue white french"), category: "Textiles" },
      { name: "Ceramic Pitcher & Lavender Set", price: 1200, link: al("ceramic pitcher white lavender artificial"), category: "Decor" },
      { name: "Blue & White Ceramic Plate Set", price: 3500, link: al("blue white ceramic plates set french country"), category: "Tableware" },
    ],
    changes: [
      { title: "Distress Your Furniture", description: "Use chalk paint or distressing techniques for a weathered, lived-in look." },
      { title: "Add a Crystal Chandelier", description: "Hang a vintage-style crystal chandelier above the dining table." },
      { title: "Use Linen Upholstery", description: "Choose natural linen fabric for dining chairs and curtains." },
      { title: "Display a Vintage Hutch", description: "Showcase ceramic plates, pitchers, and glassware in a painted hutch." },
      { title: "Hang a Gold Mirror", description: "Install an ornate gold-framed mirror to reflect light." },
      { title: "Add Fresh Flowers", description: "Always keep fresh or dried lavender, roses, or wildflowers on the table." },
    ],
    colors: [{ name: "Soft Grey", hex: "#D3D3D3" }, { name: "Cream", hex: "#FFFFF0" }, { name: "Dusty Blue", hex: "#7A8B9E" }, { name: "Antique Gold", hex: "#C9A961" }, { name: "White", hex: "#FFFFFF" }],
    totalBudget: 77700, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },
  {
    caption: "Farmhouse Kitchen",
    description: "A farmhouse kitchen with white shiplap walls, apron front sink, butcher block countertops, and open wooden shelving.",
    image: "images/gallery/farmhouse.jpg", style: "Farmhouse", weekSlot: "W3",
    products: [
      { name: "Apron Front Farmhouse Sink", price: 12000, link: al("apron front farmhouse sink white ceramic"), category: "Kitchen" },
      { name: "Butcher Block Countertop", price: 15000, link: al("butcher block countertop oak kitchen island"), category: "Kitchen" },
      { name: "Open Wooden Wall Shelves", price: 3000, link: al("open wooden wall shelves kitchen farmhouse"), category: "Storage" },
      { name: "Mason Jar Pendant Lights", price: 2500, link: al("mason jar pendant lights set of 3"), category: "Lighting" },
      { name: "Woven Jute Rug", price: 2500, link: al("woven jute rug kitchen runner"), category: "Rug" },
      { name: "Wooden Dining Table with Bench", price: 18000, link: al("wooden dining table bench set farmhouse"), category: "Furniture" },
      { name: "Woven Baskets (Set of 3)", price: 1500, link: al("woven baskets set of 3 storage farmhouse"), category: "Storage" },
      { name: "Fresh Herb Planter Set", price: 800, link: al("herb planter set kitchen window sill"), category: "Plants" },
    ],
    changes: [
      { title: "Install Shiplap Walls", description: "Add white shiplap or tongue-and-groove paneling to walls." },
      { title: "Get a Farmhouse Sink", description: "Replace your sink with a white apron-front farmhouse sink." },
      { title: "Use Butcher Block Counters", description: "Install butcher block or wood countertops for warmth." },
      { title: "Open Up Shelving", description: "Remove upper cabinets and install open wooden shelves with white dishes." },
      { title: "Add Mason Jar Lighting", description: "Hang pendant lights with mason jar shades over the island." },
      { title: "Use Natural Woven Textures", description: "Add jute rugs, wicker baskets, and linen curtains." },
    ],
    colors: [{ name: "Farmhouse White", hex: "#F5F5F0" }, { name: "Natural Wood", hex: "#C4A484" }, { name: "Sage Green", hex: "#A8BFA3" }, { name: "Charcoal", hex: "#36454F" }, { name: "Cream", hex: "#FFFFF0" }],
    totalBudget: 55300, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },

  // ===== WEEK 4: Nature & Retreat =====
  {
    caption: "Coastal Beach House",
    description: "A coastal living room with white and navy palette, whitewashed wood floors, linen sofa, and driftwood decor.",
    image: "images/gallery/coastal.jpg", style: "Coastal", weekSlot: "W4",
    products: [
      { name: "Linen Sofa with Slipcover", price: 28000, link: al("linen sofa slipcover white coastal"), category: "Furniture" },
      { name: "Driftwood Coffee Table", price: 5500, link: al("driftwood coffee table natural coastal"), category: "Furniture" },
      { name: "Navy Striped Throw Pillows (Set)", price: 1500, link: al("navy striped throw pillows set of 4"), category: "Textiles" },
      { name: "Woven Jute Area Rug", price: 3500, link: al("woven jute area rug round coastal"), category: "Rug" },
      { name: "Seashell Mirror Frame", price: 2500, link: al("seashell mirror frame round coastal"), category: "Decor" },
      { name: "Coral Branch in Glass Vase", price: 1200, link: al("coral branch decorative glass vase"), category: "Decor" },
      { name: "Woven Wicker Baskets (Set)", price: 1800, link: al("woven wicker baskets set of 3 storage"), category: "Storage" },
      { name: "Rope Pendant Light", price: 2500, link: al("rope pendant light nautical coastal"), category: "Lighting" },
    ],
    changes: [
      { title: "Use a White & Navy Palette", description: "Keep walls white and add navy blue accents through textiles." },
      { title: "Install Whitewashed Floors", description: "Use whitewashed or bleached wood flooring for a beachy feel." },
      { title: "Choose Natural Materials", description: "Use jute, rattan, driftwood, and linen throughout the space." },
      { title: "Add Coastal Decor", description: "Display shells, coral, and nautical artifacts as decorative elements." },
      { title: "Use Sheer White Curtains", description: "Hang flowing white curtains that move with the breeze." },
      { title: "Incorporate Rope Accents", description: "Use rope-wrapped lamps, mirrors, and handles for nautical charm." },
    ],
    colors: [{ name: "Coastal White", hex: "#F5F5F0" }, { name: "Navy Blue", hex: "#000080" }, { name: "Sand", hex: "#C2B280" }, { name: "Seafoam", hex: "#93E9BE" }, { name: "Driftwood", hex: "#A89F91" }],
    totalBudget: 46500, timeEstimate: "2 weekends", difficulty: "Easy",
  },
  {
    caption: "Tropical Resort Bedroom",
    description: "A tropical resort-style bedroom with white canopy bed, bamboo furniture, palm leaf prints, and lush greenery.",
    image: "images/gallery/tropical.jpg", style: "Tropical", weekSlot: "W4",
    products: [
      { name: "White Canopy Bed Frame", price: 22000, link: al("white canopy bed frame queen four poster"), category: "Furniture" },
      { name: "Bamboo & Rattan Nightstands (Pair)", price: 5500, link: al("bamboo rattan nightstands pair of 2"), category: "Furniture" },
      { name: "Palm Leaf Print Wallpaper", price: 3500, link: al("palm leaf wallpaper removable tropical"), category: "Decor" },
      { name: "Wooden Ceiling Fan", price: 4500, link: al("wooden ceiling fan tropical bamboo blades"), category: "Fixtures" },
      { name: "White Linen Bedding Set", price: 3500, link: al("white linen bedding set queen canopy"), category: "Textiles" },
      { name: "Large Tropical Plants (Set)", price: 3000, link: al("large tropical plants indoor monstera palm"), category: "Plants" },
      { name: "Wicker Pendant Light", price: 2000, link: al("wicker pendant light rattan boho tropical"), category: "Lighting" },
      { name: "Rattan Lounge Chair", price: 6000, link: al("rattan lounge chair indoor vintage"), category: "Seating" },
    ],
    changes: [
      { title: "Install a Canopy Bed", description: "Drape sheer white curtains from a four-poster bed frame." },
      { title: "Use Bamboo & Rattan", description: "Choose bamboo and rattan furniture for an authentic tropical feel." },
      { title: "Add Palm Leaf Prints", description: "Use palm leaf wallpaper or prints as an accent wall." },
      { title: "Bring in Large Plants", description: "Place monstera, palm, and bird of paradise plants around the room." },
      { title: "Use White Linens", description: "Keep bedding all white with green accent pillows." },
      { title: "Add Woven Lighting", description: "Use rattan or wicker pendant lights and lamps." },
    ],
    colors: [{ name: "Palm Green", hex: "#2D5A3D" }, { name: "White", hex: "#FFFFFF" }, { name: "Bamboo", hex: "#C8A951" }, { name: "Sand", hex: "#C2B280" }, { name: "Coral", hex: "#FF7F7F" }],
    totalBudget: 50000, timeEstimate: "2 weekends", difficulty: "Easy",
  },
  {
    caption: "Rustic Mountain Cabin",
    description: "A rustic mountain cabin bedroom with log walls, stone fireplace, fur throws, and antler chandelier.",
    image: "images/gallery/rustic.jpg", style: "Rustic", weekSlot: "W4",
    products: [
      { name: "Log Bed Frame", price: 25000, link: al("log bed frame king rustic pine"), category: "Furniture" },
      { name: "Faux Fur Throw Blankets (Set)", price: 2500, link: al("faux fur throw blanket set of 2 luxury"), category: "Textiles" },
      { name: "Leather Accent Chair", price: 12000, link: al("leather accent chair vintage brown"), category: "Seating" },
      { name: "Antler Chandelier", price: 8000, link: al("antler chandelier rustic cabin light"), category: "Lighting" },
      { name: "Plaid Bedding Set", price: 3500, link: al("plaid bedding set flannel king red"), category: "Textiles" },
      { name: "Vintage Lantern Table Lamp", price: 1800, link: al("vintage lantern table lamp rustic"), category: "Lighting" },
      { name: "Woven Southwestern Rug", price: 4500, link: al("woven southwestern rug wool large"), category: "Rug" },
      { name: "Wooden Nightstand Set", price: 3500, link: al("wooden nightstand set of 2 log cabin"), category: "Furniture" },
    ],
    changes: [
      { title: "Expose Log Walls", description: "Keep log walls visible. If not possible, use log-pattern wallpaper." },
      { title: "Add a Stone Fireplace", description: "Install or accent an existing fireplace with natural stone surround." },
      { title: "Use Fur & Leather", description: "Layer faux fur throws, leather chairs, and wool blankets." },
      { title: "Install an Antler Chandelier", description: "Hang a rustic antler or branch chandelier as the centerpiece." },
      { title: "Add Plaid Patterns", description: "Use plaid bedding, curtains, and pillows in warm red and green tones." },
      { title: "Use Warm Amber Lighting", description: "Switch to warm yellow bulbs. Add vintage lanterns and candles." },
    ],
    colors: [{ name: "Log Brown", hex: "#6B4F3A" }, { name: "Forest Green", hex: "#2D5A3D" }, { name: "Cream", hex: "#FFFFF0" }, { name: "Rust Red", hex: "#B7410E" }, { name: "Charcoal", hex: "#36454F" }],
    totalBudget: 60800, timeEstimate: "2-3 weekends", difficulty: "Medium",
  },
  {
    caption: "Contemporary Penthouse",
    description: "A contemporary luxury penthouse with marble floors, designer sectional, glass coffee table, and city skyline views.",
    image: "images/gallery/contemporary.jpg", style: "Contemporary", weekSlot: "W4",
    products: [
      { name: "Designer Grey Sectional Sofa", price: 45000, link: al("designer grey sectional sofa luxury"), category: "Furniture" },
      { name: "Glass & Chrome Coffee Table", price: 12000, link: al("glass chrome coffee table modern"), category: "Furniture" },
      { name: "Black & White Abstract Art", price: 5000, link: al("black white abstract art large canvas"), category: "Decor" },
      { name: "Statement Pendant Lights", price: 8000, link: al("statement pendant lights cluster gold black"), category: "Lighting" },
      { name: "White Marble Floor Tiles", price: 25000, link: al("white marble floor tiles polished large"), category: "Flooring" },
      { name: "Gold Accent Decor Pieces", price: 3500, link: al("gold accent decor pieces sculptures set"), category: "Decor" },
      { name: "Blackout Motorized Curtains", price: 15000, link: al("blackout motorized curtains smart electric"), category: "Automation" },
      { name: "Indoor Olive Tree", price: 4000, link: al("indoor olive tree potted large artificial"), category: "Plants" },
    ],
    changes: [
      { title: "Install Marble Flooring", description: "Use large-format white or grey marble tiles for a luxurious base." },
      { title: "Choose a Designer Sofa", description: "Invest in a high-quality sectional in grey, black, or white." },
      { title: "Add Glass Furniture", description: "Use glass coffee tables and console tables to maintain an open feel." },
      { title: "Hang Abstract Art", description: "Install large-scale black & white or monochrome abstract artwork." },
      { title: "Use Gold Accents", description: "Add gold decor, picture frames, and light fixtures for warmth." },
      { title: "Maximize Natural Light", description: "Use sheer or motorized curtains. Keep window areas unobstructed." },
    ],
    colors: [{ name: "Pure White", hex: "#FAFAFA" }, { name: "Charcoal", hex: "#474747" }, { name: "Gold", hex: "#D4AF37" }, { name: "Silver", hex: "#C0C0C0" }, { name: "Black", hex: "#1A1A1A" }],
    totalBudget: 117500, timeEstimate: "3-4 weekends", difficulty: "Advanced",
  },
  {
    caption: "Home Office Design",
    description: "A productive home office with standing desk, ergonomic chair, bookshelf, and natural light.",
    image: "images/gallery/item7.jpg", style: "Home Office", weekSlot: "W4",
    products: [
      { name: "Standing Desk (Motorized)", price: 22000, link: al("motorized standing desk electric height adjustable"), category: "Furniture" },
      { name: "Ergonomic Mesh Chair", price: 15000, link: al("ergonomic mesh office chair lumbar support"), category: "Furniture" },
      { name: "LED Desk Lamp with Wireless Charge", price: 3500, link: al("LED desk lamp wireless charger USB"), category: "Lighting" },
      { name: "Tall Bookshelf (5-tier)", price: 8000, link: al("tall bookshelf 5 tier wooden industrial"), category: "Storage" },
      { name: "Desk Organizer Set", price: 1200, link: al("desk organizer set bamboo wood"), category: "Accessories" },
      { name: "Noise-Cancelling Headphones", price: 8000, link: al("noise cancelling headphones over ear wireless"), category: "Tech" },
      { name: "Indoor Plants (Set of 3)", price: 1500, link: al("indoor plants low light set of 3"), category: "Plants" },
      { name: "Monitor Arm Stand", price: 3500, link: al("monitor arm stand single desk mount"), category: "Accessories" },
    ],
    changes: [
      { title: "Invest in Ergonomics", description: "Get a motorized standing desk and ergonomic chair. Alternate sitting and standing." },
      { title: "Maximize Natural Light", description: "Position the desk perpendicular to the window. Use sheer curtains." },
      { title: "Add a Bookshelf", description: "Install a tall bookshelf for storage and visual backdrop. Mix books with decor." },
      { title: "Upgrade Desk Lighting", description: "Get an LED desk lamp with adjustable color temperature." },
      { title: "Cable Management", description: "Use cable trays, cord covers, and a monitor arm to eliminate visible wires." },
      { title: "Add Greenery", description: "Place 2-3 low-maintenance plants on the desk and shelves." },
    ],
    colors: [{ name: "Warm White", hex: "#F5F2EA" }, { name: "Walnut Brown", hex: "#6B4F3A" }, { name: "Sage Green", hex: "#A8BFA3" }, { name: "Charcoal", hex: "#36454F" }, { name: "Beige", hex: "#E8DCC8" }],
    totalBudget: 62700, timeEstimate: "1-2 weekends", difficulty: "Easy",
  },
  {
    caption: "TV Wall Design",
    description: "An elegant TV wall with chevron wood paneling, ambient backlighting, floating shelves, and sleek media console.",
    image: "images/gallery/item9.jpg", style: "TV Wall", weekSlot: "W4",
    products: [
      { name: "Chevron Wood Wall Panels", price: 8000, link: al("chevron wood wall panels 3D adhesive"), category: "Decor" },
      { name: "TV Backlight LED Kit", price: 1500, link: al("TV backlight LED kit USB powered"), category: "Lighting" },
      { name: "Floating TV Console", price: 12000, link: al("floating TV console wall mounted media unit"), category: "Furniture" },
      { name: "Floating Display Shelves", price: 2500, link: al("floating display shelves set of 3 wall"), category: "Storage" },
      { name: "Decorative Vases (Set)", price: 2000, link: al("decorative vases set of 3 ceramic modern"), category: "Decor" },
      { name: "Cable Management Box Set", price: 800, link: al("cable management box set bamboo organizer"), category: "Accessories" },
      { name: "Tabletop Plant (Artificial)", price: 800, link: al("artificial plant tabletop realistic monstera"), category: "Decor" },
      { name: "Ambient Wall Sconces (Pair)", price: 3500, link: al("ambient wall sconces pair modern gold"), category: "Lighting" },
    ],
    changes: [
      { title: "Add Wood Paneling", description: "Install chevron, slat, or geometric wood panels behind the TV." },
      { title: "Install TV Backlight", description: "Add an LED backlight kit behind the TV for a cinema-like experience." },
      { title: "Mount a Floating Console", description: "Replace the floor TV unit with a wall-mounted floating console." },
      { title: "Add Floating Shelves", description: "Install 2-3 asymmetrical floating shelves for curated decor." },
      { title: "Hide All Cables", description: "Use in-wall cable routing or cable management boxes." },
      { title: "Balance with Lighting", description: "Add wall sconces on either side of the TV wall for ambient light." },
    ],
    colors: [{ name: "Charcoal", hex: "#36454F" }, { name: "Warm Oak", hex: "#C4A484" }, { name: "Soft White", hex: "#F5F5F0" }, { name: "Matte Black", hex: "#2B2B2B" }, { name: "Brass", hex: "#B5A642" }],
    totalBudget: 31100, timeEstimate: "1-2 weekends", difficulty: "Medium",
  },
];

async function seed() {
  const db = getDb();
  console.log(`Seeding ${items.length} gallery items...`);

  for (const item of items) {
    await db.insert(galleryItems).values(item);
  }

  console.log("Done! Seeded gallery items successfully.");
}

seed().catch(console.error);
